name: Java CI with Gradle

on:
  push:
    branches: [ main, feature/*]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21.0.7'
          distribution: 'temurin'

      - name: Prepare
        run: chmod +x gradlew

      - name: Build without test
        run: ./gradlew clean build -x test

      - name: Run test
        run: ./gradlew test

      - name: Clean and build
        run: ./gradlew clean build